Converting Matlab code example to python

In [7]:
import numpy as np

In [11]:
# A = [1,2,3;4,5,6;7,8,9;10,11,12]
A = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
print(A)
# print(A.shape) results error

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]


In [9]:
B = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(B)
print(B.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [13]:
v = np.array([[1],[2],[3]])
print(v)
print(v.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [25]:
# print(B(2,3)) is a wrong syntax
print(B[1,2])
B[1,2]

6


6

In [33]:
# A = [1, 2, 4; 5, 3, 2]
# B = [1, 3, 4; 1, 1, 1]
A = np.array([[1, 2, 4], [5, 3, 2]])
B = np.array([[1, 3, 4], [1, 1, 1]])
s = 2
print(A)
print(B)

[[1 2 4]
 [5 3 2]]
[[1 3 4]
 [1 1 1]]


In [34]:
add_AB = A + B
print(add_AB)

sub_AB = A - B
print(sub_AB)

mult_As = A * s
print(mult_As)

div_As = A / s
print(div_As)

[[2 5 8]
 [6 4 3]]
[[ 0 -1  0]
 [ 4  2  1]]
[[ 2  4  8]
 [10  6  4]]
[[0.5 1.  2. ]
 [2.5 1.5 1. ]]


In [36]:
add_As = A + s
print(add_As)
#adding a matrix A and a number s means adding the number s to all elements of matrix A

[[3 4 6]
 [7 5 4]]


In [40]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
v = np.array([[1], [1], [1]])
print(v)

[[1]
 [1]
 [1]]


In [45]:
Av = A * v
print(Av)
# A * v is not what we want. What we want is a dot product.

Av = A.dot(v)
print(Av)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 6]
 [15]
 [24]]


In [46]:
# Then what is the main difference between dot product and matmul in Python?
#simply put, for matmul, multiplication by scalars is not allowed, and stacks of matrices are broadcast together as if the matrices were elements.

From the documentation:

matmul differs from dot in two important ways.

Multiplication by scalars is not allowed.
Stacks of matrices are broadcast together as if the matrices were elements.
The last point makes it clear that dot and matmul methods behave differently when passed 3D (or higher dimensional) arrays. Quoting from the documentation some more:

For matmul:

If either argument is N-D, N > 2, it is treated as a stack of matrices residing in the last two indexes and broadcast accordingly. For np.dot:

For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation). For N dimensions it is a sum product over the last axis of a and the second-to-last of b

https://stackoverflow.com/questions/61550454/what-is-the-difference-between-numpy-dot-and-matmul-functions-in-python3

Gradient Descent For Multiple Variables

repeat until convergence:{θj:=θj−α1m∑i=1m(hθ(x(i))−y(i))⋅x(i)jfor j := 0...n